name: EliteMobsCitizen
version: ${project.version}
main: au.com.grieve.elitemobscitizens.EliteMobsCitizens
depend: [EliteMobs, Citizens]
authors: [Bundabrg]
description: Citizen support for EliteMobs
commands:
  emsk: {}